package com.eternalcode.discordapp.games;

import com.eternalcode.discordapp.config.CdnConfig;
import net.dzikoysk.cdn.entity.Description;
import net.dzikoysk.cdn.source.Resource;
import net.dzikoysk.cdn.source.Source;

import java.io.File;
import java.time.Instant;

public class CodeImageGameData implements CdnConfig {
    @Description("# This file is automatically generated, please do not edit it manually")

    public String code = "";

    public Instant lastUpdated = Instant.now();

    public boolean isUsed = false;

    public boolean gameActive = false;

    @Override
    public Resource resource(File folder) {
        return Source.of(folder, "games/imageCode.yml");
    }
}
