name: Docker Hub CI

on:
  release:
    types: [ published ]

jobs:
  docker-image-push:
    name: Push Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_AC }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Build & Push (Java 21) - EternalCode DiscordOfficer
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./docker/java21.dockerfile
          push: true
          tags: eternalcode/discordofficer:${{ github.ref_name }}-java21 , eternalcode/discordofficer:latest
          build-args: |
            OFFICER_VERSION=${{ github.ref_name }}
