name: Docker Hub CI

on:
  release:
    types: [ published ]

jobs:
  docker-image-push:
    name: Push Docker Image
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DH_USERNAME }}
          password: ${{ secrets.DH_AC }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build & Push (Java 17 image) - EternalCode DiscordOfficer
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          file: ./docker/java17.dockerfile
          push: true
          tags: eternalcode/discordofficer:${{ github.ref_name }}-java17 , eternalcode/discordofficer:latest-java17
          build-args: |
            OFFICER_VERSION=${{ github.ref_name }}
      - name: Build & Push (Java 19) - EternalCode DiscordOfficer
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          context: .
          file: ./docker/java19.dockerfile
          push: true
          tags: eternalcode/discordofficer:${{ github.ref_name }}-java19 , eternalcode/discordofficer:latest
          build-args: |
            OFFICER_VERSION=${{ github.ref_name }}
