name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Run checkstyle
        run: ./gradlew checkstyleMain
      - name: Build with Gradle
        uses: gradle/gradle-build-action@585b565652cefbba63202a7f927df0ff99f34001
        with:
          arguments: shadowJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: 'Successfully build DiscordOfficer JDK${{ matrix.jdk }}'
          path: build/libs/*.jar
