name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Run checkstyle
        run: ./gradlew checkstyleMain
      - name: Build with Gradle
        uses: gradle/gradle-build-action@243af859f8ca30903d9d7f7936897ca0358ba691
        with:
          arguments: shadowJar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'Successfully build DiscordOfficer JDK${{ matrix.jdk }}'
          path: build/libs/*.jar
